/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sockets;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author FernandoPrzGmz
 */
public class Servidor extends javax.swing.JFrame {
    private static ArrayList<ServerInterface> listClients = new ArrayList<ServerInterface>();
    private static int numID = 0;
       
    public Servidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUser = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logPanel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        logPanel.setEditable(false);
        logPanel.setColumns(20);
        logPanel.setRows(5);
        jScrollPane3.setViewportView(logPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabelUser)
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servidor().setVisible(true);
            }
        });
        
        Servidor server = new Servidor();
        server.exe();
        
    }
    
    // Funcion principal
    public void exe(){
        int PORT = 9001;
        ServerSocket server = null;
        Socket socket = null;
        
        try {
            server = new ServerSocket(PORT){
                    // Aqui se cierra el socket en la excepcion
                    protected void finalize() throws IOException {
                        this.close();
                    }
                };
            while(true) {
                // Mantener siempre aceptando conexiones
                socket = server.accept();
                System.out.format("\n\nEl cliente %s quiere conectarse.\n", socket.getInetAddress().getHostName());
                
                ServerInterface thread = new ServerInterface(socket, this);
                listClients.add(thread);
                thread.start();
                
                this.numID++;
            }
        } catch (IOException ex) {
            System.out.format("Error: %s\n", ex.getMessage());
        } finally{
            try {
                socket.close();
                server.close();
            } catch (IOException ex) {
                System.out.format("Error: cerrando los sockets %s\n", ex.getMessage());
            }
        }
    }
    
    public static ArrayList<ServerInterface> getListClients() {
        return listClients;
    }
    public static int getNumID() {
        return numID;
    }
    public static void appendMessageInLogPanel(String message) {
        logPanel.append(message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTextArea logPanel;
    // End of variables declaration//GEN-END:variables
}
